const docx = require("docx");
const fs = require("fs");
const path = require("path");
const { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun, Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle, Header, Footer, PageNumber, TableLayoutType, VerticalAlign } = docx;

const SD = "/home/z/my-project/download/screenshots";
const OP = "/home/z/my-project/download/Munyaradzi_Patama_B221315B_Chapter_4.docx";
const MT=1440,MB=1440,ML=1701,MR=1417,FE="Times New Roman",FC="SimSun";

function ls(f){const p=path.join(SD,f);if(!fs.existsSync(p)){console.error("WARN: "+p);return null;}return fs.readFileSync(p);}
function gi(b,cm){const mw=cm*360000;let w=1920,h=1080;try{w=b.readUInt32BE(16);h=b.readUInt32BE(20);}catch(e){}return{mw,mh:Math.round(mw/(w/h))};}
function bp(t){return new Paragraph({alignment:AlignmentType.JUSTIFIED,spacing:{line:360,before:0,after:120},indent:{firstLine:480},children:[new TextRun({text:t,font:{name:FE,eastAsia:FC},size:24})]});}
function h1(t){return new Paragraph({heading:HeadingLevel.HEADING_1,alignment:AlignmentType.CENTER,spacing:{before:240,after:240,line:360},children:[new TextRun({text:t,bold:true,font:{name:FE,eastAsia:FC},size:32})]});}
function h2(t){return new Paragraph({heading:HeadingLevel.HEADING_2,alignment:AlignmentType.LEFT,spacing:{before:240,after:120,line:360},children:[new TextRun({text:t,bold:true,font:{name:FE,eastAsia:FC},size:30})]});}
function h3(t){return new Paragraph({heading:HeadingLevel.HEADING_3,alignment:AlignmentType.LEFT,spacing:{before:200,after:120,line:360},children:[new TextRun({text:t,bold:true,font:{name:FE,eastAsia:FC},size:28})]});}
function fc(t){return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:100,after:160,line:360},children:[new TextRun({text:t,font:{name:FE,eastAsia:FC},size:21,bold:true})]});}
function tc(t){return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:160,after:100,line:360},children:[new TextRun({text:t,font:{name:FE,eastAsia:FC},size:21,bold:true})]});}
function ip(b,cm){const d=gi(b,cm);return new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:100,after:0},children:[new ImageRun({data:b,transformation:{width:Math.round(d.mw/9525),height:Math.round(d.mh/9525)},type:"png"})]});}
function img(fn,cm,cap){const i=ls(fn);const e=[];if(i)e.push(ip(i,cm));e.push(fc(cap));return e;}
function ct(h,r,cw){
  const nb={style:BorderStyle.NONE,size:0,color:"FFFFFF"},tb={style:BorderStyle.SINGLE,size:12,color:"000000"},bb={style:BorderStyle.SINGLE,size:12,color:"000000"},tbb={style:BorderStyle.SINGLE,size:6,color:"000000"};
  function hc(t,w){return new TableCell({width:{size:w,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,borders:{top:tb,bottom:tbb,left:nb,right:nb},children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:30,after:30,line:320},children:[new TextRun({text:t,bold:true,font:{name:FE,eastAsia:FC},size:20})]})]});}
  function dc(t,w,l){return new TableCell({width:{size:w,type:WidthType.DXA},verticalAlign:VerticalAlign.CENTER,borders:{top:nb,bottom:l?bb:nb,left:nb,right:nb},children:[new Paragraph({alignment:AlignmentType.LEFT,spacing:{before:16,after:16,line:300},indent:{left:60},children:[new TextRun({text:t,font:{name:FE,eastAsia:FC},size:19})]})]});}
  return new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({tableHeader:true,children:h.map((x,i)=>hc(x,cw[i]))}),...r.map((row,ri)=>new TableRow({children:row.map((c,ci)=>dc(c,cw[ci],ri===r.length-1))}))],layout:TableLayoutType.FIXED});
}

async function gen(){
console.log("Generating Chapter 4 (15 pages)...");
const c=[
  h1("CHAPTER 4: SYSTEM DESIGN AND IMPLEMENTATION"),
  h2("4.0 Introduction"),
  bp("This chapter presents the detailed design and implementation of the Network Infrastructure Security Assessment and Action Platform (NISAAP), a web-based IoT security management system developed specifically for the National Railways of Zimbabwe (NRZ). The chapter systematically documents the architectural decisions, technology selections, database design, and implementation details of each functional module. The system was designed to address the critical security gaps identified in the vulnerability assessment of NRZ's IoT infrastructure, as discussed in the preceding chapters."),
  bp("The platform was conceived as a comprehensive solution to manage, monitor, and mitigate security risks associated with the growing deployment of Internet of Things devices across NRZ's railway operations. These IoT devices, which include signal controllers, CCTV cameras, track sensors, network gateways, routers, and GPS trackers, form the operational backbone of the railway network and require robust security management to ensure both operational continuity and passenger safety."),
  bp("The chapter begins with the system architecture and technology stack, followed by the database design and the implementation of each functional module, including authentication, dashboard, IoT device management, vulnerability management, security solutions, assessment, audit logging, user management, and the dark mode feature. The chapter also presents the REST API design, system security considerations, testing validation, and a chapter summary."),

  h2("4.1 System Architecture"),
  bp("The NISAAP platform was designed using a three-tier architecture that separates the presentation layer, application logic layer, and data persistence layer. This pattern was selected for its benefits in maintainability, scalability, and security, allowing each layer to be developed and modified independently."),
  bp("The presentation tier was implemented using Next.js 16 with React, providing a responsive and interactive user interface that communicates with the application tier exclusively through RESTful API endpoints. The user interface was constructed using Tailwind CSS 4 and shadcn/ui for consistent, accessible component design. Client-side state is managed through the Zustand library, which maintains the current user session, active navigation view, sidebar state, and dark mode preference in a centralised store."),
  bp("The application tier was implemented using Next.js API Routes, which provide a Node.js-based server environment integrated within the Next.js framework, eliminating the need for a separate backend server. The API layer implements the business logic for all functional modules with a consistent authentication verification pattern enforced through the checkAuth function. The data persistence tier utilises SQLite accessed through the Prisma ORM framework, providing type-safe database queries and automatic migration management."),
  ...img("02_dashboard.png",10,"Figure 4-1: NISAAP Dashboard Overview Showing System Architecture Components"),

  h2("4.2 Technology Stack"),
  tc("Table 4-1: NISAAP Technology Stack Overview"),
  ct(["Category","Technology","Version","Purpose"],[["Frontend Framework","Next.js (React)","16","Server-side rendering, routing, UI framework"],["Programming Language","TypeScript","5.x","Type-safe JavaScript for reduced runtime errors"],["CSS Framework","Tailwind CSS","4","Utility-first CSS for responsive styling"],["UI Component Library","shadcn/ui","Latest","Accessible, customisable UI components"],["State Management","Zustand","5.x","Lightweight client-side state management"],["Backend Runtime","Node.js (via Next.js)","22.x","Server-side JavaScript execution environment"],["API Architecture","Next.js API Routes","16","RESTful endpoint handlers within Next.js"],["Database Engine","SQLite","3","Embedded relational database for persistence"],["ORM Framework","Prisma","6.x","Type-safe database access and migration management"],["Authentication","JWT (Cookie-based)","Custom","Session management with HTTP-only cookies"],["Password Hashing","Node.js scrypt","Built-in","Memory-hard key derivation for password security"],["Charting Library","Recharts","2.x","Data visualisation for dashboards and analytics"]],[2200,2400,1200,5000]),
  bp("The decision to use Next.js 16 was driven by its unified development model for both frontend and backend. TypeScript was adopted for its static type system, and combined with Prisma's type-safe query API, creates a fully type-safe data pipeline from the database to the user interface. For authentication, the system implements a custom session-based mechanism using Node.js's built-in scrypt key derivation function, which provides resistance against brute-force and rainbow table attacks. The user interface uses NRZ's corporate brand colours, including Navy Blue (#003366), Gold (#C5A55A), Dark Navy (#1A2B4A), and contextual colours for risk indicators."),

  h2("4.3 Database Design"),
  bp("The database design follows a relational model defined using Prisma's declarative schema definition language, which automatically generates SQL migration scripts. The design prioritises data integrity through foreign key constraints, cascade deletion rules, and unique field constraints."),
  ...img("10_prisma_schema.png",11,"Figure 4-2: Prisma Schema Definition for the NISAAP Database Models"),
  tc("Table 4-2: NISAAP Database Models Summary"),
  ct(["Model","Key Fields","Relationships","Records"],[["User","id, username, email, fullName, role, department, isActive","Has many Assessments, AuditLogs","10"],["IoTDevice","deviceName, deviceType, ipAddress, location, station, status, riskLevel","Has many Vulnerabilities, Assessments","31"],["Vulnerability","deviceId, title, description, severity, cvssScore, cveId, status","Belongs to IoTDevice; Has many SecuritySolutions","26"],["SecuritySolution","vulnerabilityId, title, implementationStatus, priority, costEstimate","Belongs to Vulnerability","22"],["Assessment","deviceId, assessorId, findings, recommendations, riskRating","Belongs to IoTDevice, User","14"],["AuditLog","userId, action, module, details, ipAddress, timestamp","Belongs to User (optional)","93"]],[1600,3200,3200,800]),
  bp("The User model stores authentication credentials and role information with scrypt-hashed passwords using a 16-byte salt and 64-byte derived key, supporting three role levels: admin, analyst, and viewer. The IoTDevice model captures comprehensive device information including type, location, risk level, and network configuration. The Vulnerability model represents security weaknesses with severity classification, CVSS scoring, and CVE tracking, with lifecycle states of open, acknowledged, in_progress, resolved, and accepted_risk. The SecuritySolution model links remediation actions to vulnerabilities. The Assessment model records formal security assessments, and the AuditLog model provides an append-only record of all user actions."),

  h2("4.4 System Implementation"),
  bp("This section presents the detailed implementation of each functional module within the NISAAP platform. The implementation follows a modular design where each module encapsulates its own business logic, API endpoints, and user interface components."),

  h3("4.4.1 Authentication Module"),
  bp("The authentication module serves as the primary security gateway, controlling access through a username and password verification process. The module validates credentials using the scrypt key derivation function with the timingSafeEqual comparison function to prevent timing attacks."),
  ...img("01_login_page.png",9,"Figure 4-3: NISAAP Login Page with Secure Authentication Interface"),
  bp("The authentication process follows a multi-step verification workflow: validating required fields, retrieving the user record, checking account activation status, and verifying the password using scrypt. Upon success, the system creates an HTTP-only session cookie with SameSite=Strict and Max-Age=86400 attributes, which mitigate XSS, CSRF, and session hijacking attacks. Failed attempts are logged in the audit log. The module enforces role-based access control through three roles: admin, analyst, and viewer."),
  ...img("11_auth_api.png",11,"Figure 4-4: Authentication API Implementation Code"),

  h3("4.4.2 Dashboard Module"),
  bp("The dashboard module provides a comprehensive overview of the IoT security landscape, aggregating data from all modules into a unified visual interface with key performance indicators, risk distribution charts, severity breakdowns, and recent activity logs."),
  ...img("02_dashboard.png",9,"Figure 4-5: NISAAP Dashboard Module with Security Statistics and Visualisations"),
  bp("The dashboard aggregates real-time security metrics including total devices, active devices, open vulnerabilities, and critical alerts. The severity distribution chart uses distinct colours: critical in red, high in amber, medium in gold, and low in green. The dashboard API endpoint implements authentication verification and uses Prisma's aggregation and grouping functions for efficient statistics computation."),
  ...img("12_dashboard_api.png",11,"Figure 4-6: Dashboard Statistics API Implementation Code"),

  h3("4.4.3 IoT Device Management Module"),
  bp("The IoT Device Management module provides comprehensive functionality for managing IoT devices across the NRZ railway network. The module presents a searchable, filterable inventory with full CRUD operations, displaying device name, type, IP address, location, station, status, and risk level."),
  ...img("04_iot_devices.png",9,"Figure 4-7: IoT Device Management Module with Device Inventory and Risk Indicators"),
  bp("The 31 seeded devices are categorised into six types: controllers for signalling, cameras for surveillance, sensors for track monitoring, gateways for communication aggregation, routers for traffic management, and trackers for GPS location. The risk level indicator is automatically recalculated when vulnerabilities change. The module implements filtering by type, status, risk level, and station, along with search functionality using case-insensitive substring matching."),

  h3("4.4.4 Vulnerability Management Module"),
  bp("The Vulnerability Management module is the core security analysis component, providing functionality for documenting, tracking, and resolving security vulnerabilities with associated device, severity, CVSS score, CVE identifier, and remediation status."),
  ...img("05_vulnerabilities.png",9,"Figure 4-8: Vulnerability Management Module with Severity Classifications and CVSS Scores"),
  bp("The module tracks each vulnerability through five status stages: open, acknowledged, in_progress, resolved, and accepted_risk. Each record includes a CVSS score on a 0.0 to 10.0 scale. The 26 seeded vulnerabilities include critical items such as unencrypted signal communication protocols (CVSS 9.8), default credentials on CCTV systems (CVSS 9.1), and buffer overflow vulnerabilities in point machine controllers (CVSS 9.7). The vulnerability creation endpoint implements an automatic device risk level recalculation mechanism."),

  h3("4.4.5 Security Solutions Module"),
  bp("The Security Solutions module provides a structured framework for managing vulnerability remediation, presenting solutions linked to their associated vulnerabilities with implementation status, priority level, assigned analyst, and cost estimate."),
  ...img("06_security_solutions.png",9,"Figure 4-9: Security Solutions Module with Implementation Tracking and Priority Levels"),
  bp("The module tracks implementation through four statuses: proposed, in_progress, implemented, and verified. The priority system categorises solutions as critical, high, medium, or low. The 22 seeded solutions include TLS 1.3 encryption for signal communications, emergency firmware patching, and routing infrastructure hardening. Each solution includes cost estimates for budget planning and an assigned analyst for accountability."),

  h3("4.4.6 Assessment Module"),
  bp("The Assessment module supports the formal security assessment process for IoT devices, documenting evaluation findings, recommendations, and risk ratings. The 14 seeded assessments cover a representative sample of IoT devices across different types and stations."),
  ...img("07_assessments.png",9,"Figure 4-10: Assessment Module with Device Security Evaluation Records"),

  h3("4.4.7 Audit Log Module"),
  bp("The Audit Log module provides comprehensive activity tracking across all NISAAP modules, creating an immutable record of user actions for security monitoring, compliance reporting, and forensic investigation. The 93 seeded entries include actions such as LOGIN, LOGIN_FAILED, CREATE, UPDATE, and DELETE. The audit log is append-only, ensuring trail integrity."),
  ...img("08_audit_logs.png",9,"Figure 4-11: Audit Log Module with Comprehensive Activity Tracking"),

  h3("4.4.8 User Management Module"),
  bp("The User Management module provides administrators with the ability to create, view, modify, and deactivate user accounts. The module is restricted to administrator-level access. Passwords are hashed using scrypt before storage, and account deactivation uses the isActive flag rather than deletion to preserve audit log integrity."),
  ...img("03_user_management.png",9,"Figure 4-12: User Management Module with Role-Based Access Control Interface"),

  h3("4.4.9 Dark Mode Feature"),
  bp("The platform includes a dark mode feature optimised for low-light environments and extended monitoring sessions, particularly relevant for NRZ's security operations centre during night shifts. The implementation uses Zustand for state management and localStorage for preference persistence, with styling through Tailwind CSS's dark: variant prefix. The colour palette maintains WCAG-compliant contrast ratios."),
  ...img("09_dark_mode_dashboard.png",9,"Figure 4-13: NISAAP Dashboard in Dark Mode with Reduced Glare Interface"),

  h2("4.5 REST API Design"),
  tc("Table 4-3: NISAAP REST API Endpoints"),
  ct(["Module","Method","Endpoint","Description"],[["Authentication","POST","/api/auth/login","User login with credential verification"],["Authentication","POST","/api/auth/logout","User logout and session destruction"],["Authentication","GET","/api/auth/session","Retrieve current session information"],["Users","GET","/api/users","List all users with role information"],["Users","GET/PUT/DELETE","/api/users/[id]","Get, update, or delete a specific user"],["Dashboard","GET","/api/dashboard/stats","Retrieve aggregated security statistics"],["Devices","GET/POST","/api/devices","List or create IoT device records"],["Devices","GET/PUT/DELETE","/api/devices/[id]","Get, update, or delete a specific device"],["Vulnerabilities","GET/POST","/api/vulnerabilities","List or create vulnerability records"],["Vulnerabilities","GET/PUT/DELETE","/api/vulnerabilities/[id]","Get, update, or delete a vulnerability"],["Solutions","GET/POST","/api/solutions","List or create security solution records"],["Solutions","GET/PUT/DELETE","/api/solutions/[id]","Get, update, or delete a solution"],["Assessments","GET/POST","/api/assessments","List or create assessment records"],["Assessments","GET/PUT/DELETE","/api/assessments/[id]","Get, update, or delete an assessment"],["Audit Logs","GET","/api/audit-logs","List all audit log entries"],["Root","GET","/api/route","API health check and endpoint listing"]],[1800,1400,3200,4000]),
  bp("The API was designed to be stateless and uniform, adhering to REST architectural constraints. The endpoints follow a consistent naming convention with plural resource nouns and hierarchical paths. The API enforces authentication on all endpoints except login, with each protected endpoint verifying the session cookie. Error handling returns structured JSON responses with appropriate HTTP status codes, and all data modification operations trigger audit log entries."),

  h2("4.6 System Security Considerations"),
  tc("Table 4-4: NISAAP Security Measures and Threat Mitigation"),
  ct(["Security Measure","Implementation","Protection Against"],[["Password Hashing","scrypt with 16-byte salt and 64-byte key","Brute-force and rainbow table attacks"],["HTTP-only Cookie","HttpOnly flag prevents JavaScript access","XSS session token theft"],["SameSite Cookie","SameSite=Strict attribute","Cross-site request forgery (CSRF)"],["Session Expiry","Max-Age=86400 (24 hours)","Session hijacking and replay attacks"],["Timing-Safe Comparison","timingSafeEqual for password verification","Timing side-channel attacks"],["Input Validation","Required field checks on all endpoints","Injection and data integrity attacks"],["Role-Based Access Control","Three-tier role hierarchy","Unauthorised privilege escalation"],["Audit Logging","Comprehensive action logging","Unauthorised activity and compliance gaps"],["SQL Injection Prevention","Prisma ORM parameterised queries","SQL injection attacks"],["Error Handling","Generic server error messages","Information disclosure vulnerabilities"]],[2600,3400,4400]),
  bp("The NISAAP platform was designed with security as a fundamental architectural principle, incorporating multiple layers of protection following the principle of defence in depth. The authentication system uses scrypt password hashing with unique random salts, HTTP-only session cookies to mitigate XSS, SameSite=Strict to prevent CSRF, and 24-hour session expiry. The timingSafeEqual function prevents timing side-channel attacks. Prisma ORM provides automatic SQL query parameterisation to prevent injection attacks, and the role-based access control system implements least privilege with comprehensive audit logging."),

  h2("4.7 System Testing and Validation"),
  tc("Table 4-5: NISAAP System Test Cases and Results"),
  ct(["Test Category","Test Case","Expected Result","Status"],[["Authentication","Valid credentials login","Session cookie created, user data returned","Passed"],["Authentication","Invalid password login","401 response, LOGIN_FAILED audit log","Passed"],["Authentication","Deactivated account login","401 response with deactivation message","Passed"],["CRUD Operations","Create new device record","Device created, audit log entry generated","Passed"],["CRUD Operations","Update vulnerability status","Status updated, audit log generated","Passed"],["Filtering","Filter devices by risk level","Only matching devices returned","Passed"],["RBAC","Viewer attempts data modification","403 Forbidden response","Passed"],["RBAC","Analyst attempts user management","403 Forbidden response","Passed"],["Dashboard","Statistics accuracy verification","Counts match database totals","Passed"],["Audit Log","CRUD operations generate log entries","All operations logged correctly","Passed"],["Dark Mode","Toggle and persist preference","Theme persists after page reload","Passed"]],[1800,2800,3200,1200]),
  bp("System testing was conducted throughout the development lifecycle to ensure each functional module met its specified requirements. Authentication testing verified session cookie creation, invalid credential handling, and audit logging of failed attempts. Module-level testing validated CRUD operations, filtering, search, and automatic risk level recalculation. RBAC testing confirmed appropriate access privileges for each role. The dark mode feature was tested across all views with WCAG 2.1 Level AA contrast validation."),

  h2("4.8 Chapter Summary"),
  bp("This chapter has presented the comprehensive design and implementation of the Network Infrastructure Security Assessment and Action Platform (NISAAP), a web-based IoT security management system developed for the National Railways of Zimbabwe. The system was designed using a three-tier architecture with a technology stack comprising Next.js 16, TypeScript, Tailwind CSS 4, Prisma ORM, and SQLite, selected to balance security, performance, and operational simplicity."),
  bp("The database design defines six core models supporting the full IoT security management lifecycle. The implementation of nine functional modules provides a comprehensive suite of security management tools addressing the specific requirements identified in the vulnerability assessment of NRZ's IoT infrastructure. The REST API design provides a secure interface with consistent authentication, error handling, and audit logging. The system security considerations documented the multiple layers of protection implemented, and system testing validated the functional correctness, security properties, and user experience of each module."),
  bp("The NISAAP platform demonstrates that a focused, well-designed web application can effectively address the IoT security challenges facing railway operators. The platform's modular architecture supports future expansion, including the potential integration of real-time threat intelligence feeds, automated vulnerability scanning, and machine learning-based anomaly detection, which would further enhance NRZ's ability to protect its IoT infrastructure against evolving cyber threats."),
];

const doc=new Document({
  styles:{default:{document:{run:{font:{name:FE,eastAsia:FC},size:24},paragraph:{spacing:{line:360}}},heading1:{run:{font:{name:FE,eastAsia:FC},size:32,bold:true},paragraph:{alignment:AlignmentType.CENTER,spacing:{before:240,after:240,line:360}}},heading2:{run:{font:{name:FE,eastAsia:FC},size:30,bold:true},paragraph:{alignment:AlignmentType.LEFT,spacing:{before:240,after:120,line:360}}},heading3:{run:{font:{name:FE,eastAsia:FC},size:28,bold:true},paragraph:{alignment:AlignmentType.LEFT,spacing:{before:200,after:120,line:360}}}}},
  sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:MT,bottom:MB,left:ML,right:MR}}},headers:{default:new Header({children:[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:60},border:{bottom:{style:BorderStyle.SINGLE,size:6,color:"000000"}},children:[new TextRun({text:"NISAAP System Design and Implementation",font:{name:FE,eastAsia:FC},size:18,color:"666666"})]})]})},footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],font:{name:FE,eastAsia:FC},size:20})]})]})},children:c}]
});
const buf=await Packer.toBuffer(doc);
fs.writeFileSync(OP,buf);
console.log("Done: "+OP+" ("+(buf.length/1024).toFixed(1)+" KB)");
}
gen().catch(e=>{console.error(e);process.exit(1);});
